name: rec-building

on:
  watch:
    types: [started]
    
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
      
   - name: wget
      uses: wei/wget@v1
      with:
        args: https://down.warbler.cc/d/LZYs/GSI/Flyme/AB/Flyme9-16T-AB-10-2021.06.05-LZYGSI.7z 
        
    
    - name: Upload REC
      uses: softprops/action-gh-release@v1
      with:
        files: /home/runner/Flyme9-16T-AB-10-2021.06.05-LZYGSI.7z
        name: gsi
        tag_name: ${{ github.run_id }}
        body: Android Third-Party Recovery built by ${{ steps.var.outputs.git_username }}
      env:
        GITHUB_TOKEN: ${{ secrets.helpmi }}
  
